//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimePunchDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting
    {
        public long ID { get; set; }
        public int minimumLunchMins { get; set; }
        public string payPeriodStartDate { get; set; }
        public int payPeriodDays { get; set; }
    }
}
